export const WIDTH_PLAYER=10;
export const HEIGHT_PLAYER=WIDTH_PLAYER*10;

export const MOVEMENT_PLAYER=WIDTH_PLAYER*1.7

export const WIDTH_BOARD=WIDTH_PLAYER*80;

export const HEIGHT_BOARD=WIDTH_PLAYER*50;